#!/usr/bin/env python3
from dotenv import load_dotenv
import os
from core.ivi import IVI
from core.ava import AVA
from core.eve import EVE

def main():
    weather_api_key = os.getenv('WEATHER_API_KEY')
    calendar_credentials_file = os.getenv('GOOGLE_CALENDAR_CREDENTIALS')
    ava = AVA()
    ivi = IVI(weather_api_key, calendar_credentials_file)
    eve = EVE()

    while True:
        user_input = ivi.interface()
        if user_input.lower() == "exit":
            break
        aurora_response = ivi.process_data(user_input)
        eve.convert_text_to_speech(aurora_response)
        print("Aurora: " + aurora_response + "\n")
        eve.play_response()

if __name__ == "__main__":
    main()
